---
- name: Agregando repositorio para install mysql
  yum_repository:
    name: mysql
    description: Repositorio yum para instalar MySQL
    baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
  
- name: Agregando la clave GPG del repo de MySQL
  rpm_key:
    state: present
    key: http://repo.mysql.com/RPM-GPG-KEY-mysql

- name: Instalando mysql-server
  yum:
    name: mysql-server
    state: latest

- name: Instalando mysql-python (se necesita para cambiar la clave del administrador de la base de datos con Ansible)
  yum:
    name: MySQL-python
    state: latest

- name: Arrancando MySQL Server y habilitarlo
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Cambiando la clave aleatoria por omisión de MySQL
  shell: |
    password_match=`awk '/A temporary password is generated for/ {a=$0} END{ print a }' /var/log/mysqld.log | awk '{print $(NF)}'`
    echo $password_match
    mysql -uroot -p$password_match --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '"{{db_root_password}}"'; flush privileges; "
    echo -e ""[client]"\nuser=root\npassword="{{db_root_password}}"" > /root/.my.cnf

- name: restart mysqld
  service: 
    name: mysqld 
    state: restarted
